# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesBDbinary <- function(obs, inimean, nrun, nburn, J, slice, outputAll) {
    .Call('BayesBD_BayesBDbinary', PACKAGE = 'BayesBD', obs, inimean, nrun, nburn, J, slice, outputAll)
}

BayesBDnormal <- function(obs, inimean, nrun, nburn, J, slice, outputAll) {
    .Call('BayesBD_BayesBDnormal', PACKAGE = 'BayesBD', obs, inimean, nrun, nburn, J, slice, outputAll)
}

eigenfun <- function(n,x) {
    .Call('BayesBD_eigenfun', PACKAGE = 'BayesBD', n,x)
}

unisliceL <- function(x0, gx0, i_J, tauini, anini, alphalambda, betalambda, lambdaini) {
    .Call('BayesBD_unisliceL', PACKAGE = 'BayesBD', x0, gx0, i_J, tauini, anini, alphalambda, betalambda, lambdaini)
}
