# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesBDbinary <- function(obs, inimean, nrun, nburn, J, slice) {
    .Call('BayesBDet_BayesBDbinary', PACKAGE = 'BayesBDet', obs, inimean, nrun, nburn, J, slice)
}

BayesBDnormal <- function(obs, inimean, nrun, nburn, J, slice) {
    .Call('BayesBDet_BayesBDnormal', PACKAGE = 'BayesBDet', obs, inimean, nrun, nburn, J, slice)
}

eigenfun <- function(n,x) {
    .Call('BayesBDet_eigenfun', PACKAGE = 'BayesBDet', n,x)
}

unisliceL <- function(x0, gx0, i_J, tauini, anini, alphalambda, betalambda, lambdaini) {
    .Call('BayesBDet_unisliceL', PACKAGE = 'BayesBDet', x0, gx0, i_J, tauini, anini, alphalambda, betalambda, lambdaini)
}
